# Generated by Django 6.0.1 on 2026-01-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_in_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='in_stock',
            new_name='stock',
        ),
    ]
