# Generated by Django 6.0.1 on 2026-02-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
