# Generated by Django 4.2.11 on 2026-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_menuitem_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержимое страницы'),
        ),
    ]
