# Generated by Django 4.2.11 on 2026-02-05 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_menuitem_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.menuitem', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Изображение страницы',
                'verbose_name_plural': 'Изображения страниц',
                'ordering': ['order'],
            },
        ),
    ]
