# Generated by Django 6.0.2 on 2026-02-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_options_product_is_new_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
