# Generated by Django 6.0.2 on 2026-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_price',
            field=models.BooleanField(default=False, verbose_name='Скрыть цену'),
        ),
    ]
